fix(github): Fail build on Beachball check
Resolves issue with the builds passing on failed Beachball checks.

Fixes #400.

diff --git a/.github/workflows/workspace.yml b/.github/workflows/workspace.yml
--- a/.github/workflows/workspace.yml
+++ b/.github/workflows/workspace.yml
@@ -30,8 +30,11 @@ jobs:
       - name: Beachball
         if: github.event_name == 'pull_request'
         run: |
-          pnpm bechball check || \
-          echo "::error::Beachball changes detected. Run 'pnpm beachball change' and commit the changes."
+          pnpm beachball check ||
+          (
+            echo "::error::Beachballchanges detected. Run 'pnpm beachball change' and commit the changes.";
+            exit 1
+          )
 
       - name: Sort packages
         run: |
